CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers_db (
  id INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(60) NOT NULL,
  devoured BOOLEAN DEFAULT FALSE,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
